#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'chrome'
cookbook 'java'
cookbook 'mongodb'
cookbook 'mozilla-firefox'
cookbook 'postgresql'
cookbook 'xvfb'
